from typing import Dict, Any, Optional, Protocol

class PanelProtocol(Protocol):
    """Base protocol for panel interfaces."""
    def setup_ui(self) -> None: ...
    def validate_inputs(self) -> bool: ...
    def get_configuration(self) -> Dict[str, Any]: ...
